apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-html
data:
  index.html: |
    <html>
    <body style="background:#28a745; color:white; text-align:center; font-family:Arial;">
      <h1>APP 2</h1>
      <p>This is the GREEN app served via NGINX.</p>
    </body>
    </html>
