apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-html
data:
  index.html: |
    <html>
    <body style="background:#007bff; color:white; text-align:center; font-family:Arial;">
      <h1>APP 1</h1>
      <p>This is the BLUE app served via NGINX.</p>
    </body>
    </html>
